### ISSUE TITLE
Unable to connect to any account after a logout

### ISSUE THREAD

**Issue by arthur-mdn** [BUT-MMI3/VisioConf#47]

**Comment by mathis-lambert** [comment]
Yes merci d'avoir ouvert l'issue, je crois que j'ai une idée d'où ça vient

**Comment by mathis-lambert** [comment]
Bizarre, pour l'instant j'ai un comportement normal, si je me déconnecte avec la popup et que je me reconnecte ca fonctionne

**Comment by arthur-mdn** [comment]
Pourtant le bug est toujours présent. Check sur l'instance de ton VPS visioconf.mathislambert... 
Connecte toi à un compte (par exemple admin), ouvre la modale de déconnexion en cliquant sur l'image de profil en bas de la barre de menu, et réessaie de te connecter. Il y a des messages dans la console client mais on reste bloqué sur la page login

**Comment by mathis-lambert** [comment]
Bah c'est vraiment méga bizarre, en local quand on se déconnecte et se reconnecte direct ca fonctionne mais oui effectivement sur la prod non

**Comment by mathis-lambert** [comment]
ok j'ai trouvé le problème

**Comment by mathis-lambert** [comment]
Fixed with #55
