### ISSUE TITLE
Many server errors 

### ISSUE THREAD

**Issue by arthur-mdn** [BUT-MMI3/VisioConf#68]
Server errors 

**Steps to reproduce the behavior**
1. Login
2. See error in api-express logs

<img width="1259" alt="image" src="https://github.com/BUT-MMI3/VisioConf/assets/108630737/84d57058-ffa0-4b7b-b91a-3811d9e3d61b">

**Comment by mathis-lambert** [comment]
hello, comment t'as eu ce comportement ???
je viens de me login sur la prod et j'ai pas d'erreur

**Comment by mathis-lambert** [comment]
<img width="516" alt="image" src="https://github.com/BUT-MMI3/VisioConf/assets/93223257/7064f28f-acd4-48cc-81cf-2c537a05cbc3">

**Comment by arthur-mdn** [comment]
J'ai simplement pull la branche main !
Au début j'ai cru à des conflits de paquets alors j'ai suppr "node_modules" et refait une install complète, mais j'ai toujours les erreurs..
et les erreurs sont en boucle dans la console server, sans faire d'actions côté client

**Comment by mathis-lambert** [comment]
euh bah c'est vraiment chelou, que je soit en local ou en prod y'a pas d'erreur

**Comment by mathis-lambert** [comment]
la ligne 81 de app.js gère les erreur 404 donc tu dois avoir un programme actif sur ton ordi qui tape sur l'adresse du serveur mais qui n'est pas censé le faire

**Comment by arthur-mdn** [comment]
Bien vu ! J'ai changé les ports, et ça a réglé le souci, je n'ai pourtant rien d'autre qui tourne derrière .. 
Bizarre..
